Group.delete_all

Group.create!(name: 'AQUA', kind: :kg)
Group.create!(name: 'Arch', kind: :kg)
Group.create!(name: 'Auto-ID', kind: :kg)
Group.create!(name: 'Bianco', kind: :kg)
Group.create!(name: 'CPSF', kind: :kg)
Group.create!(name: 'haccar', kind: :kg)
Group.create!(name: 'ISC', kind: :kg)
Group.create!(name: 'kumo', kind: :kg)
Group.create!(name: 'Life-Colud', kind: :kg)
Group.create!(name: 'LINK', kind: :kg)
Group.create!(name: 'MEMSYS', kind: :kg)
Group.create!(name: 'NECO', kind: :kg)
Group.create!(name: 'Sociable Robots', kind: :kg)
Group.create!(name: 'faculty', kind: :other)
